### ISSUE TITLE
Empty sequence when getting optimal assignment

### ISSUE THREAD

**Issue by desh2608** [fgnt/graph_pit#3]
When using the OptimalDynamicProgramming method for assignment, on some inputs I get an error on this line:
https://github.com/fgnt/graph_pit/blob/9eaf6edce321cf4a5a01582bd77758709541f489/graph_pit/assignment.py#L417
`ValueError: min() arg is an empty sequence`

This is probably because the adjacency list must be sorted at the beginning of this function when the `neighbors` are computed (as mentioned in the comment), which I suppose means that the `segment_boundaries` must be provided in sorted order. Perhaps this can be mentioned in the usage example?

**Comment by desh2608** [comment]
Hmm, weird. I still get the empty sequence even when the segment boudaries are sorted. Any ideas what may be going wrong?

**Comment by desh2608** [comment]
After some digging, it seems the error was occurring due to 3-fold overlapping segments. Sorry about the flurry of comments! You can close this issue.

**Comment by thequilo** [comment]
Hi @desh2608! I actually had the same issue a while back. I have some code lying around to improve the error message, I'll merge that.

> This is probably because the adjacency list must be sorted at the beginning of this function when the neighbors are computed (as mentioned in the comment), which I suppose means that the segment_boundaries must be provided in sorted order. Perhaps this can be mentioned in the usage example?

That's actually a good point.
