### ISSUE TITLE
Generate valid training sequence

### ISSUE THREAD

**Issue by quancs** [fgnt/graph_pit#9]
Hello, can you provide some ideas on how to generate the training sequence that is valid for graph-pit? Or is there any way to quickly find if a given graph has the solution or not

**Comment by thequilo** [comment]
Hi @quancs!

The idea behind Graph-PIT is that you have continuous (i.e. uninterrupted) regions of activity with a start and end timestamp. The graph is generated from these timestamps. A sequence has a graph-pit solution if it consists of continuous activity segments and the number of segments that overlap at the same point in time is not larger than the number of output streams of the system.

How you generate this depends on the use case. If you want to do meeting separation, you can sample utterances from a source dataset and place them such that they fulfill the conditions mentioned above. I used https://github.com/fgnt/mms_msg for my experiments. But note that way the data is generated has a large impact on the final network performance.

There is code to generate a valid overlap graph in the tests https://github.com/fgnt/graph_pit/blob/b930f7a7f6cab5a8bc3b99e78b91f54b880c558d/tests/test_graph_assignment_solver.py#L12.
But I'm not sure if this helps for generating training sequences.

**Comment by quancs** [comment]
OK, I will try. Thank you.
